DROP TABLE IF EXISTS part;

CREATE TABLE part (
  id SERIAL PRIMARY KEY,
  category_name VARCHAR(255),
  part_code VARCHAR(255),
  part_name VARCHAR(255),
  color_code VARCHAR(255),
  color_name VARCHAR(255),
  sales_country VARCHAR(255),
  bricklink_url VARCHAR(255),
  sold_new_times_sold VARCHAR(255),
  sold_new_total_qty VARCHAR(255),
  sold_new_min_price VARCHAR(255),
  sold_new_avg_price VARCHAR(255),
  sold_new_qty_avg_price VARCHAR(255),
  sold_new_max_price VARCHAR(255),
  sold_used_times_sold VARCHAR(255),
  sold_used_total_qty VARCHAR(255),
  sold_used_min_price VARCHAR(255),
  sold_used_avg_price VARCHAR(255),
  sold_used_qty_avg_price VARCHAR(255),
  sold_used_max_price VARCHAR(255),
  listed_new_total_lots VARCHAR(255),
  listed_new_total_qty VARCHAR(255),
  listed_new_min_price VARCHAR(255),
  listed_new_avg_price VARCHAR(255),
  listed_new_qty_avg_price VARCHAR(255),
  listed_new_max_price VARCHAR(255),
  listed_used_total_lots VARCHAR(255),
  listed_used_total_qty VARCHAR(255),
  listed_used_min_price VARCHAR(255),
  listed_used_avg_price VARCHAR(255),
  listed_used_qty_avg_price VARCHAR(255),
  listed_used_max_price VARCHAR(255),
  date_created VARCHAR(255)
);
